apiVersion: v1
kind: Service
metadata:
  name: skaffold-nestjs-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: skaffold-nestjs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-nestjs
  template:
    metadata:
      labels:
        app: skaffold-nestjs
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: skaffold-nestjs
          image: registry.gitlab.com/svtslv/skaffold-nestjs-angular/dev-skaffold-nestjs
          ports:
            - containerPort: 3000
